### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by vkinakh** [StanfordMIMI/skm-tea#1]
Hi!
Is it possible to access the SKM-TEA dataset? I cannot find the link in the paper or in the repository.
Thanks!

**Comment by ad12** [comment]
Thanks for your interest! You can download the dataset at the link below:
 
https://stanfordaimi.azurewebsites.net/datasets/4aaeafb9-c6e6-4e3c-9188-3aaaf0e0a9e7
 
Please note that the data sharing and paper are undergoing some final processing and will be ready by the Neurips camera ready deadline (early November). There will also be guidelines for how to use the dataset and how to compute/report metrics for standardized comparison at that time.
