### ISSUE TITLE
T2 map

### ISSUE THREAD

**Issue by huangchaoxing** [StanfordMIMI/skm-tea#18]
Did you provide the T2 maps calculated from ground-truth  E1 and E2 ? 

Thank you

**Comment by ad12** [comment]
T2 maps are not precomputed, but can be computed from E1/E2 using the [dosma](https://github.com/ad12/dosma) package. A tutorial on how to do this can be found [here](https://colab.research.google.com/drive/1PluqK77pobD5dXE7zzBLEAeBgaaeGKXa).

**Note:** The "ground-truth" T2 maps will be different for the DICOM track and the Raw Data Track.
- For the DICOM track, ground-truth T2 maps are constructed from the E1/E2 in the `image_files` folder in the dataset and the segmentation masks in `segmentation_masks/dicom-track`
- For the Raw Data track, ground truth T2 maps use E1/E2 from the `files_recon_calib-24` folder and segmentation masks in `segmentation_masks/raw-data-track`

**Comment by ad12** [comment]
Closing this request for now, but please feel free to reopen / post again if there's anything I can help with.
