### ISSUE TITLE
Register train, test, valid split

### ISSUE THREAD

**Issue by aldiak** [StanfordMIMI/skm-tea#21]
Hi, I have a train, test, and validation split, so how do I register that to DataCatalog?

**Comment by ad12** [comment]
thank for the question @aldiak! Just to make sure I understand:
1. Do you want to register your train/val/test splits of a different dataset or the SKM-TEA dataset
2. If these splits are for the SKM-TEA dataset, are you trying to register your own splits or the publicly available splits?

**Comment by aldiak** [comment]
Hello, I already have the data locally with the recon files in three
folders (train, test and Val). The other are as downloaded (no split)

**Comment by aldiak** [comment]
It’s actually SKM-Tea dataset

**Comment by aldiak** [comment]
I registered, but got the following issue too.

**Comment by ad12** [comment]
The folder structure should not change - all files should stay in the folders they were in during download.

When you downloaded the data, you likely got a folder `v1-release`. Place this folder inside a parent folder called `</path/to/dataset/directory>/skm-tea`. `</path/to/dataset/directory>` can be any parent directory.

To make the `skm-tea` package auto-detect the dataset, add this to the top of your script/code:

```python
import os
os.environ["MEDDLR_DATASETS_DIR"] = "</path/to/dataset/directory>"
```

**Comment by aldiak** [comment]
Alright, by doing so I do not need to change the paths in the function
get_path defined in register.py file, right?

**Comment by ad12** [comment]
Yup, you shouldn't have to change any paths.

**Comment by aldiak** [comment]
Alright, I will let you know about the outcome. Thanks

**Comment by ad12** [comment]
Picking up the conversation from [this thread](https://github.com/ad12/meddlr/issues/67)

## Overview
I don't believe this has to do with data registration - your datasets are loading fine:
```python
2022-10-22 12:42:10,859 - Dropped 0 scans. 86 scans remaining
2022-10-22 12:42:10,859 - Dropped references for 0/86 scans. 86 scans with reference remaining
2022-10-22 12:42:11,496 - Loading D:/files_recon_calib-24/annotations/val.json takes 0.00 seconds
2022-10-22 12:42:13,993 - Formatting dataset dicts takes 2.49 seconds
2022-10-22 12:42:13,993 - Dropped 0 scans. 33 scans remaining
2022-10-22 12:42:13,993 - Dropped references for 0/33 scans. 33 scans with reference remaining
```

It looks like this is happening when running `precompute_masks`. You may have to precompute masks with `cfg.DATALOADER.NUM_WORKERS=0`. To do this, add `DATALOADER.NUM_WORKERS 0` to the end of the script you are running:

```python
python train_net.py <your-current-args> DATALOADER.NUM_WORKERS 0
```

**Comment by aldiak** [comment]
Hi, thank you the data is loading fine now
