### ISSUE TITLE
k-space data undersampled or (synthesized) unsampled?

### ISSUE THREAD

**Issue by guanhuaw** [StanfordMIMI/skm-tea#4]
Hi @ad12 , thanks for such a great contribution to our community.

I have two minor questions about the k-space data:
1) the y direction is under-sampled, while the paper suggests that 'unsampled k-space data was subsequently synthesized using Autocalibrating Reconstruction for Cartesian imaging (ARC)'
2) according to the appendix, the size of the readout direction is 416 and padded to 512. However, the k-space data does not have zero elements near the edge.

Not sure if these questions are just features of the Orchestra toolbox. Thanks in advance!

**Comment by guanhuaw** [comment]
Another little one: the appendix does not show the FOV and resolution in the z direction.

**Comment by ad12** [comment]
Hi @guanhuaw, thanks for your interest in the dataset and for these questions! Adding some details below

1. The ky direction is fully-sampled in the elliptical region (see image below). The scan was acquired with 2x1 parallel imaging with elliptical sampling. ARC was used to synthesize the k-space data in the elliptical region.
2. The kspace has been hybridized such that the matrix structure is `(x, ky, kz)`. To use the 3D kspace, where all dimensions correspond to the kspace domain, undo the hybridization by taking the fft along the x dimension.
3. Thanks for this note - we will add the FOV and resolution in the z-direction in the updated manuscript

![coils](https://user-images.githubusercontent.com/12801331/144170098-013f1ec1-3db9-40df-99b8-17630cfe8b23.png)

**Comment by guanhuaw** [comment]
Thanks for the reply! The cvs header file shows that the slice thickness is 1.6mm and slice spacing is 0.8mm. The z-axis resolution, accordingly, is 2.4mm?

**Comment by ad12** [comment]
The nominal acquisition resolution along the z direction is 1.6mm. This direction is then zero-padded to 2x the matrix size (following ZIP2 protocol), so the effective z-resolution of the zero-padded data (and DICOM images) is 0.8mm.

**Comment by guanhuaw** [comment]
Thanks again for the further help!
